name: CI 

on:
  pull_request:

jobs:
  build:
    runs-on: verific-builder
    steps:
      - name: Cancel previous
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: Runner workspace path
        run: |
          echo "Cleaning up previous run"
          rm -rf "${{ github.workspace }}"
          mkdir -p "${{ github.workspace }}"

      - uses: actions/checkout@v2

      - name: Checkout submodules
        run: |
          git submodule update --init --recursive --progress

      - name: Configure shell
        run: |
          echo "/usr/local/bin" >> $GITHUB_PATH

      - name: Build yosys+verific
        run:
          make release

      - name: Export environment variables
        run: |
          echo "ABC=$GITHUB_WORKSPACE/yosys_verific_rs/build/logic_synthesis-rs/bin/abc" >> $GITHUB_ENV
          echo "DE=$GITHUB_WORKSPACE/yosys_verific_rs/build/logic_synthesis-rs/bin/de" >> $GITHUB_ENV
          echo "LSORACLE=$GITHUB_WORKSPACE/yosys_verific_rs/build/logic_synthesis-rs/bin/lsoracle" >> $GITHUB_ENV

      - name: Run tests
        run: |
          cd yosys-rs-plugin
          make test YOSYS_PATH=$(realpath ../yosys/install)
