name: Daily tests

on:
  schedule:
    - cron: "30 19 * * 1,2,3,4,5"
  workflow_dispatch:

jobs:
  build:
    runs-on: verific-builder
    steps:
      - name: Cancel previous
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - uses: actions/setup-python@v2
        if: ${{ false }} # We don't have permissions on 'verific-builder'
        with:
          python-version: 3.8

      - name: ssh-agent
        uses: webfactory/ssh-agent@v0.5.4
        with: 
          ssh-private-key: |
            ${{ secrets.SSH_PRIVATE_KEY_VERIFIC }}
            ${{ secrets.SSH_PRIVATE_KEY_RTL_BENCHMARK }}
            ${{ secrets.SSH_PRIVATE_KEY_YOSYS }}
            ${{ secrets.SSH_PRIVATE_KEY_YOSYS_RS_PLUGIN }}
            ${{ secrets.SSH_PRIVATE_KEY_ABC }}
            ${{ secrets.SSH_PRIVATE_KEY_LOGIC_SYNTHESIS }}
            ${{ secrets.SSH_PRIVATE_KEY_LSORACLE }}

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install dependencies
        if: ${{ false }} # We don't have permissions on 'verific-builder'
        working-directory: ./.github/scripts
        run: |
          bash install_ubuntu_dependencies_build.sh
          python3 -m pip install --upgrade pip --user
          python3 -m pip install pandas termcolor --user

      - name: Use ccache
        if: ${{ false }} # We don't have permissions on 'verific-builder'
        uses: hendrikmuhs/ccache-action@v1
        with:
          key: linux-gcc
  
      - name: Configure shell
        run: |
          echo 'CC=gcc' >> $GITHUB_ENV
          echo 'CXX=g++' >> $GITHUB_ENV
          echo 'PATH=/usr/lib/ccache:'"$PATH" >> $GITHUB_ENV
          echo 'PREFIX=/tmp/yosys_verific-install' >> $GITHUB_ENV
          echo "ADDITIONAL_CMAKE_OPTIONS='-DMY_CXX_WARNING_FLAGS="-W -Wall -Wextra -Wno-unused-parameter -Wno-unused-variable -Werror -UNDEBUG"'" >> $GITHUB_ENV
          echo 'RULE_MESSAGES=off' >> $GITHUB_ENV
  
      - name: Show shell configuration
        run: |
          env
          which cmake && cmake --version
          which make && make --version
          which python && python --version
          which ninja && ninja --version
          which $CC && $CC --version
          which $CXX && $CXX --version

      - name: Build yosys+verific
        run:
          make release
          
      - name: Execute Python script
        continue-on-error: true
        run: |
          python3 scripts/synth/synthesis.py --config_files suites/Golden/Golden_synth_rs_ade.json

      - name: Upload logs
        uses: actions/upload-artifact@v2
        with:
          name: logs
          path: result*/

      - name: Execute metrics extraction
        continue-on-error: true
        run:
          python3 scripts/log_automation/run_metrics_extractor.py --yosys result*/Golden_synth_rs_ade.json .github/logs/Golden_synth_rs_ade  --output_file Golden_synth_rs_ade.csv --run_log result*/run.log .github/logs/Golden_synth_rs_ade/run.log --base .github/logs/Golden_synth_rs_ade

      - name: Upload csv file
        uses: actions/upload-artifact@v2
        with:
          name: cvs
          path: Golden_synth_rs_ade.csv

      - name: Compare QoR
        run: |
          python3 scripts/log_automation/result_comparision.py Golden_synth_rs_ade.csv
