name: Test

on:
  workflow_dispatch:
  schedule:
    - cron: "30 19 * * 1,2,3,4"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        mode:
        - build
        - test
    steps:
      - name: Cancel previous
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: Runner workspace path
        run: |
          echo "Cleaning up previous run"
          rm -rf "${{ github.workspace }}"
          mkdir -p "${{ github.workspace }}"

      - name: os-release
        if: matrix.mode == 'build'
        run: |
          cat /etc/os-release

      - name: issue
        if: matrix.mode == 'test' && github.event.schedule
        run: |
          cat /etc/issue
