name: Test

on:
  workflow_dispatch:
  schedule:
    - cron: "30 19 * * 1,2,3,4"

jobs:
  build:
    runs-on: verific-builder
    steps:
      - name: Cancel previous
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
  
      - name: Configure shell
        run: |
          echo 'CC=gcc' >> $GITHUB_ENV
          echo 'CXX=g++' >> $GITHUB_ENV
          echo 'PATH=/usr/lib/ccache:'"$PATH" >> $GITHUB_ENV
          echo 'PREFIX=/tmp/yosys_verific-install' >> $GITHUB_ENV
          echo "ADDITIONAL_CMAKE_OPTIONS='-DMY_CXX_WARNING_FLAGS="-W -Wall -Wextra -Wno-unused-parameter -Wno-unused-variable -Werror -UNDEBUG"'" >> $GITHUB_ENV
          echo 'RULE_MESSAGES=off' >> $GITHUB_ENV
  
      - name: Show shell configuration
        run: |
          env
          which cmake && cmake --version
          which make && make --version
          which python && python --version
          which ninja && ninja --version
          which $CC && $CC --version
          which $CXX && $CXX --version
