name: Increment Version

on:
  pull_request:
    types: [opened]

jobs:
  increment-patch-version:
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
    - name: Cancel previous
      uses: styfle/cancel-workflow-action@0.9.1
      with:
        access_token: ${{ github.token }}

    - name: Checkout code
      uses: actions/checkout@v4
      with:
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Increment patch version
      run: |
        bash scripts/increment_version.sh

    - name: Commit changes
      uses: EndBug/add-and-commit@v9.1.4
      with:
        message: 'Incremented patch version'
        committer_name: GitHub Actions
        add: 'CMakeLists.txt'
