name: Weekly Regression tests

on:
  schedule:
    - cron: "15 11 * * *"

jobs:
  build:
    runs-on: verific-builder
    steps:
      - name: Cancel previous
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: Runner workspace path
        run: |
          echo "Cleaning up previous run"
          rm -rf "${{ github.workspace }}"
          mkdir -p "${{ github.workspace }}"

      - uses: actions/checkout@v2

      - name: Checkout and build yosys+verific
        run:
          make co_and_build_yosys_verific

      - name: Clone RTL benchmarks and itc99-poli 
        run: |
          make co_benchmark_name BENCHMARK_NAME=RTL_Benchmark
          make co_benchmark_name BENCHMARK_NAME=itc99-poli
        
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip --user
          python3 -m pip install pandas --user
          
      - name: Execute Python script
        run: |
          python3 scripts/synth/synthesis.py --config_files suites/All/All_lut_rs_abc_a21.json

      - name: Upload logs
        uses: actions/upload-artifact@v2
        with:
          name: logs
          path: result*/

      - name: Create run.log
        run: |
          cp result*/run.log ./
          cat .github/logs/All_lut_vivado/All_lut_vivado_run.log >> run.log

      - name: Execute metrics extraction
        run:
          python3 scripts/log_automation/run_metrics_extractor.py --vivado .github/logs/All_lut_vivado/ --yosys result*/All_lut_rs_abc_a21.json/ --output_file All_lut.csv --run_log run.log --base .github/logs/All_lut_vivado/
        
      - name: Upload csv file
        uses: actions/upload-artifact@v2
        with:
          name: cvs
          path: All_lut.csv
